extends: 'eslint:recommended'
env:
    worker: true
    browser: true
    es6: true
parser: babel-eslint
parserOptions:
    sourceType: module
    ecmaVersion: 8
rules:
    indent:
    - off
    linebreak-style:
    - error
    - unix
    quotes:
    - error
    - single
    semi:
    - error
    - never
    no-cond-assign:
    - off
    quote-props:
    # make sure you understand the implications of turning this off
    # https://developers.google.com/closure/compiler/docs/limitations#implications-of-global-variable,-function,-and-property-renaming:
    - error
    - always
globals:
    AWS_REGION: false
    AWS_ACCESS_KEY_ID: false
    AWS_SECRET_ACCESS_KEY: false
